const lessonData = {};

lessonData["01_AldrichAmes.mp3"] = [{
    text: "Aldrich Ames was a high-ranking officer in the CIA. His job was to find Soviet spies, but he had a secret problem: he needed money for his expensive life. In 1985, he decided to sell American secrets to the Soviet Union. For nine years, he gave the Soviets the names of almost every agent working for the US inside Russia. Because of his betrayal, many of these agents were arrested and executed. Ames received millions of dollars for his work as a double agent. He bought a fast car and a big house, which made the FBI very suspicious. After a long investigation, they found proof in his trash and arrested him in 1994. He was sent to prison for the rest of his life. This was one of the most damaging cases in the history of American intelligence because Ames destroyed the entire network of US spies in the Soviet Union.",
    dict: { "high-ranking": "üst düzey", "officer": "subay/memur", "find": "bulmak", "spies": "casuslar", "secret": "gizli", "problem": "sorun", "needed": "ihtiyacı vardı", "money": "para", "expensive": "pahalı", "life": "hayat", "decided": "karar verdi", "sell": "satmak", "secrets": "sırlar", "names": "isimler", "almost": "neredeyse", "agent": "ajan", "working": "çalışan", "inside": "içinde", "Because": "çünkü", "betrayal": "ihanet", "many": "birçok", "arrested": "tutuklandı", "executed": "idam edildi", "received": "aldı", "millions": "milyonlar", "double agent": "çift taraflı ajan", "bought": "satın aldı", "fast": "hızlı", "house": "ev", "suspicious": "şüpheli", "investigation": "soruşturma", "found": "buldu", "proof": "kanıt", "trash": "çöp", "sent": "gönderildi", "prison": "hapishane", "rest": "geri kalan", "damaging": "zarar verici", "cases": "vakalar", "history": "tarih", "intelligence": "istihbarat", "destroyed": "yok etti", "entire": "bütün/tüm", "network": "ağ" },
    questions: [ {q:"Did Ames find Soviet spies for his job?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell American secrets for no money?", a_en:"No", a_tr:"Hayır"}, {q:"Did he give the Soviets the names of US agents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his betrayal cause the death of nobody?", a_en:"No", a_tr:"Hayır"}, {q:"Did the FBI find proof in his trash?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sent to prison for life?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he destroy the entire network of US spies?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["02_AshrafMarwan.mp3"] = [{
    text: "Ashraf Marwan was a very powerful man in Egypt. He was the son-in-law of the Egyptian President and a close advisor to the government. Because of his position, he knew all of Egypt's military secrets. In 1969, he contacted the Israeli intelligence agency and offered to be a spy. The Israelis gave him the code name 'The Angel.' For several years, he gave Israel very important information about Egypt's plans for war. His most famous moment happened in 1973. He warned Israel that Egypt and Syria were going to attack the very next day. This allowed Israel to prepare for the Yom Kippur War just in time. Marwan died in 2007 when he fell from a balcony in London. Some people believe he was a true spy for Israel, while others think he was a double agent who was actually working for Egypt.",
    dict: { "powerful": "güçlü", "man": "adam", "son-in-law": "damat", "President": "Başkan", "close": "yakın", "advisor": "danışman", "government": "hükümet", "position": "konum", "knew": "biliyordu", "military": "askeri", "secrets": "sırlar", "contacted": "iletişime geçti", "intelligence": "istihbarat", "agency": "ajans/teşkilat", "offered": "teklif etti", "spy": "casus", "code": "kod", "name": "isim", "Angel": "Melek", "several": "birkaç", "years": "yıllar", "gave": "verdi", "important": "önemli", "information": "bilgi", "plans": "planlar", "war": "savaş", "famous": "ünlü", "moment": "an", "happened": "oldu/gerçekleşti", "warned": "uyardı", "attack": "saldırmak", "next": "sonraki", "day": "gün", "allowed": "izin verdi/sağladı", "prepare": "hazırlanmak", "just in time": "tam zamanında", "died": "öldü", "fell": "düştü", "balcony": "balkon", "believe": "inanıyor", "true": "gerçek", "while": "iken", "think": "düşünüyor", "double agent": "çift taraflı ajan", "actually": "aslında", "working": "çalışan" },
    questions: [ {q:"Was Marwan the son-in-law of the Egyptian President?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he know nothing about Egypt's military secrets?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Israelis give him the code name 'The Angel'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he warn Israel about an attack in 1973?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Israel prepare for the war just in time?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Marwan die by falling from a balcony?", a_en:"Yes", a_tr:"Evet"}, {q:"Do some people think he was a double agent for Egypt?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["03_DonnieBrasco.mp3"] = [{
    text: "Joe Pistone was an FBI agent who carried out a very dangerous undercover mission. He used the name 'Donnie Brasco' and pretended to be a jewel thief. His goal was to infiltrate the Bonanno crime family in New York. Pistone was so good at his job that the Mafia members trusted him like a brother. He spent six years living a double life. He had to be very careful every day because if the Mafia found out he was a cop, they would kill him. He recorded many conversations and learned about murders and robberies. When the mission ended in 1981, his evidence led to over 200 arrests of top Mafia leaders. The Mafia was so angry that they offered $500,000 to anyone who could kill him. Pistone had to live in hiding for many years. His story is one of the most successful examples of police infiltration in history.",
    dict: { "agent": "ajan", "carried out": "gerçekleştirdi", "dangerous": "tehlikeli", "undercover": "gizli", "mission": "görev", "used": "kullandı", "pretended": "numara yaptı", "jewel": "mücevher", "thief": "hırsız", "goal": "hedef", "infiltrate": "sızmak", "crime": "suç", "family": "aile", "good": "iyi", "job": "iş", "members": "üyeler", "trusted": "güvendiler", "brother": "erkek kardeş", "spent": "geçirdi", "living": "yaşayarak", "double life": "ikili hayat", "careful": "dikkatli", "found out": "öğrense", "cop": "polis", "kill": "öldürmek", "recorded": "kaydetti", "conversations": "konuşmalar", "learned": "öğrendi", "murders": "cinayetler", "robberies": "soygunlar", "ended": "bitti", "evidence": "kanıt", "led to": "yol açtı", "arrests": "tutuklamalar", "top": "en üst/lider", "leaders": "liderler", "angry": "öfkeli", "offered": "teklif etti", "anyone": "herhangi biri", "live": "yaşamak", "hiding": "saklanma", "story": "hikaye", "successful": "başarılı", "examples": "örnekler", "infiltration": "sızma", "history": "tarih" },
    questions: [ {q:"Did Joe Pistone pretend to be a jewel thief?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he want to infiltrate the Bonanno crime family?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Mafia trust him like a brother?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his evidence lead to no arrests?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Mafia offer money to kill him?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Pistone have to live in hiding?", a_en:"Yes", a_tr:"Evet"}, {q:"Is his story a successful example of police infiltration?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["04_DuskoPopov.mp3"] = [{
    text: "Duško Popov was a wealthy man from Yugoslavia who became a legendary double agent during World War II. He was very charming and loved a luxury life with fast cars and fancy parties. The Nazis recruited him to spy on Britain, but he immediately went to the British and offered to work for them. The British gave him the code name 'Tricycle.' He gave the Nazis fake information that was actually written by British intelligence. He was so trusted by the Germans that they gave him a lot of money and even a special camera to take photos. One of his most important moments was when he tried to warn the Americans about the attack on Pearl Harbor, but they paid him no attention. Popov’s real-life adventures were so exciting and dangerous that he was the main inspiration for the character James Bond.",
    dict: { "wealthy": "zengin", "legendary": "efsanevi", "double agent": "çift taraflı ajan", "during": "sırasında", "charming": "çekici/büyüleyici", "loved": "sevdi", "luxury": "lüks", "life": "hayat", "fast": "hızlı", "cars": "arabalar", "fancy": "süslü/lüks", "parties": "partiler", "recruited": "işe aldı", "spy": "casusluk yapmak", "immediately": "derhal", "went": "gitti", "offered": "teklif etti", "work": "çalışmak", "code name": "kod adı", "fake": "sahte", "information": "bilgi", "actually": "aslında", "written": "yazılmış", "intelligence": "istihbarat", "trusted": "güvenilen", "money": "para", "special": "özel", "camera": "kamera", "photos": "fotoğraflar", "important": "önemli", "moments": "anlar", "tried": "denedi", "warn": "uyarmak", "attack": "saldırı", "paid": "ödediler (verdiler)", "no": "hiç/yok", "attention": "dikkat", "real-life": "gerçek hayat", "adventures": "maceralar", "exciting": "heyecan verici", "dangerous": "tehlikeli", "main": "ana", "inspiration": "ilham", "character": "karakter" },
    questions: [ {q:"Was Popov a wealthy man from Yugoslavia?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British give him the code name 'Tricycle'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the Nazis real British secrets?", a_en:"No", a_tr:"Hayır"}, {q:"Did the Germans trust him and give him money?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Americans pay him no attention regarding Pearl Harbor?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the main inspiration for James Bond?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he love a luxury life with fast cars?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["05_EddieChapman.mp3"] = [{
    text: "Eddie Chapman was a professional criminal in England before World War II. The Germans captured him and trained him to be a spy. They dropped him into England by parachute with a mission to blow up a factory. However, Chapman went straight to the British police and offered to work for them instead. The British gave him the code name 'Agent Zigzag.' They helped him fake the explosion at the factory using smoke and camouflage to trick German planes. The Germans believed he was a hero and gave him a high military medal. For the rest of the war, he gave the Nazis fake information while secretly helping the British. He was a very brave and clever man who lived a life of constant danger. He is the only British citizen to receive a medal from Germany while working as a double agent.",
    dict: { "professional": "profesyonel", "criminal": "suçlu", "before": "önce", "captured": "esir aldı/yakaladı", "trained": "eğitti", "spy": "casus", "dropped": "bıraktı/attı", "parachute": "paraşüt", "mission": "görev", "blow up": "havaya uçurmak", "factory": "fabrika", "straight": "doğrudan", "police": "polis", "offered": "teklif etti", "instead": "bunun yerine", "code name": "kod adı", "helped": "yardım etti", "fake": "sahte yapmak", "explosion": "patlama", "using": "kullanarak", "smoke": "duman", "camouflage": "kamuflaj", "trick": "kandırmak", "planes": "uçaklar", "believed": "inandı", "hero": "kahraman", "high": "yüksek", "military": "askeri", "medal": "madalya", "rest": "geri kalan", "war": "savaş", "information": "bilgi", "secretly": "gizlice", "helping": "yardım ederek", "brave": "cesur", "clever": "zeki", "constant": "sürekli", "danger": "tehlike", "only": "tek", "citizen": "vatandaş", "receive": "almak", "double agent": "çift taraflı ajan" },
    questions: [ {q:"Was Eddie Chapman a professional criminal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British give him the code name 'Agent Zigzag'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he trick German planes with smoke and camouflage?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Germans give him no medals?", a_en:"No", a_tr:"Hayır"}, {q:"Did he give the Nazis fake information?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he the only British citizen to receive a German medal?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live a life of constant danger?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["06_EliCohen.mp3"] = [{
    text: "Eli Cohen was a legendary Israeli spy who was born in Egypt. He was recruited by Mossad to infiltrate the Syrian government. He moved to Damascus and pretended to be a rich Syrian businessman named Kamel Amin Thaabet. He became close friends with top military generals and leaders. Cohen was so successful that he was even invited to visit secret military bunkers. While there, he suggested that the soldiers plant trees for shade. These trees later helped the Israeli army see exactly where the bunkers were. He sent secret messages back to Israel every night using a radio. However, Syrian security caught him in 1965 using special equipment. He was executed in public, but he is remembered as one of Israel's greatest heroes because his information helped them win the Six-Day War.",
    dict: { "legendary": "efsanevi", "spy": "casus", "born": "doğdu", "recruited": "işe alındı", "infiltrate": "sızmak", "government": "hükümet", "moved": "taşındı", "pretended": "numara yaptı", "rich": "zengin", "businessman": "iş adamı", "named": "adında", "close": "yakın", "friends": "arkadaşlar", "top": "üst düzey", "military": "askeri", "generals": "generaller", "leaders": "liderler", "successful": "başarılı", "invited": "davet edildi", "visit": "ziyaret etmek", "secret": "gizli", "bunkers": "sığınaklar", "suggested": "önerdi", "soldiers": "askerler", "plant": "dikmek", "trees": "ağaçlar", "shade": "gölge", "later": "daha sonra", "helped": "yardım etti", "army": "ordu", "see": "görmek", "exactly": "tam olarak", "messages": "mesajlar", "night": "gece", "using": "kullanarak", "radio": "radyo", "security": "güvenlik", "caught": "yakaladı", "special": "özel", "equipment": "ekipman", "executed": "idam edildi", "public": "halk", "remembered": "hatırlanır", "greatest": "en büyük", "heroes": "kahramanlar", "information": "bilgi", "win": "kazanmak" },
    questions: [ {q:"Was Eli Cohen an Israeli spy born in Egypt?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he pretend to be a rich Syrian businessman?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he suggest planting trees for shade near bunkers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the trees help the Israeli army see the bunkers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send messages to Israel using no radio?", a_en:"No", a_tr:"Hayır"}, {q:"Did Syrian security catch him using special equipment?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he remembered as one of Israel's greatest heroes?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["07_GeorgeBlake.mp3"] = [{
    text: "George Blake was a high-level officer in the British MI6 intelligence agency. During the Korean War, he was captured and became a communist. He decided to secretly work for the Soviet Union. When he returned to England, he started giving the KGB the names of hundreds of Western agents. He also told the Soviets about a secret tunnel the Americans and British built under Berlin to listen to phone lines. Because of Blake, the Soviets knew about the tunnel from the first day. For many years, the British had no idea that their colleague was a traitor. Finally, he was caught and sentenced to 42 years in prison. However, in 1966, he escaped from a London prison and fled to the Soviet Union, where he lived the rest of his life.",
    dict: { "high-level": "üst düzey", "officer": "subay/memur", "intelligence": "istihbarat", "agency": "ajans/teşkilat", "During": "sırasında", "War": "Savaş", "captured": "esir alındı", "became": "oldu", "communist": "komünist", "decided": "karar verdi", "secretly": "gizlice", "work": "çalışmak", "returned": "geri döndü", "started": "başladı", "giving": "vermeye", "names": "isimler", "hundreds": "yüzlerce", "Western": "Batılı", "agents": "ajanlar", "told": "söyledi", "tunnel": "tünel", "built": "inşa ettiler", "under": "altında", "listen": "dinlemek", "phone lines": "telefon hatları", "Because of": "yüzünden", "knew": "biliyordu", "first": "ilk", "day": "gün", "years": "yıllar", "no idea": "hiçbir fikri yoktu", "colleague": "meslektaş", "traitor": "hain", "caught": "yakalandı", "sentenced": "hüküm giydi", "prison": "hapishane", "escaped": "kaçtı", "fled": "kaçtı/sığındı", "lived": "yaşadı", "rest": "geri kalan", "life": "hayat" },
    questions: [ {q:"Was George Blake an officer in MI6?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he decide to secretly work for the Soviet Union?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell the Soviets about a secret tunnel under Berlin?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British know about his betrayal from the first day?", a_en:"No", a_tr:"Hayır"}, {q:"Was he sentenced to 42 years in prison?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he escape from prison in 1966?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he flee to the Soviet Union to live the rest of his life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["08_HarrietTubman.mp3"] = [{
    text: "Harriet Tubman is famous for helping slaves escape to freedom, but she was also a spectacular spy during the American Civil War. Because she knew the land very well, the Union Army asked her to lead a network of spies. Tubman recruited local people to find out where the enemy soldiers were hiding their supplies. She was very brave and often traveled behind enemy lines in disguise. In June 1863, she became the first woman in American history to lead a military raid. She guided steamboats up a river, avoiding underwater mines she had mapped out. During this mission, she helped free more than 700 slaves and destroyed enemy storehouses. She was a brilliant leader and intelligence officer who used her skills to help win the war for freedom.",
    dict: { "famous": "ünlü", "helping": "yardım etme", "slaves": "köleler", "escape": "kaçmak", "freedom": "özgürlük", "spectacular": "muhteşem", "spy": "casus", "Civil War": "İç Savaş", "knew": "biliyordu", "land": "toprak/arazi", "Army": "Ordu", "asked": "istedi", "lead": "yönetmek", "network": "ağ", "recruited": "işe aldı", "local": "yerel", "find out": "öğrenmek/bulmak", "enemy": "düşman", "soldiers": "askerler", "hiding": "saklayan", "supplies": "erzak/malzeme", "brave": "cesur", "traveled": "seyahat etti", "behind": "arkasında", "lines": "hatlar", "disguise": "kılık değiştirme", "first": "ilk", "woman": "kadın", "history": "tarih", "military": "askeri", "raid": "baskın", "guided": "rehberlik etti", "steamboats": "buharlı gemiler", "river": "nehir", "avoiding": "kaçınarak", "underwater": "sualtı", "mines": "mayınlar", "mapped out": "haritasını çıkardığı", "mission": "görev", "free": "özgür kılmak", "destroyed": "yok etti", "storehouses": "depolar", "brilliant": "parlak/zeki", "intelligence": "istihbarat", "officer": "subay", "skills": "yetenekler", "win": "kazanmak" },
    questions: [ {q:"Is Harriet Tubman famous for helping slaves escape?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Union Army ask her to lead a network of spies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she travel behind enemy lines in disguise?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she lead a military raid in 1863?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she guide steamboats and hit underwater mines?", a_en:"No", a_tr:"Hayır"}, {q:"Did she help free more than 700 slaves?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she a brilliant intelligence officer?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["09_JuanPujolGarcia.mp3"] = [{
    text: "Juan Pujol García was a Spanish man who wanted to help the British during World War II. He pretended to be a Nazi supporter and convinced the Germans to hire him. He moved to Portugal and sent the Germans fake reports about England using only maps and a tourist book. He created a fake network of 27 imaginary spies to make the Germans believe he was very powerful. Eventually, the British realized he was brilliant and gave him the code name 'Agent Garbo.' His most important mission was tricking Hitler about D-Day. He convinced the Germans that the real invasion would happen in a different place. Even after the invasion started, Hitler kept his best soldiers away because he believed Garbo's fake messages. He is one of the most successful double agents in history.",
    dict: { "wanted": "istedi", "help": "yardım etmek", "during": "sırasında", "pretended": "numara yaptı", "supporter": "destekçi", "convinced": "ikna etti", "hire": "işe almak", "moved": "taşındı", "sent": "gönderdi", "fake": "sahte", "reports": "raporlar", "using": "kullanarak", "maps": "haritalar", "tourist": "turist", "book": "kitap", "created": "yarattı", "network": "ağ", "imaginary": "hayali", "spies": "casuslar", "make": "yapmak", "believe": "inanmak", "powerful": "güçlü", "Eventually": "Sonunda", "realized": "fark etti", "brilliant": "parlak/zeki", "code name": "kod adı", "important": "önemli", "mission": "görev", "tricking": "kandırma", "real": "gerçek", "invasion": "işgal", "happen": "olmak/gerçekleşmek", "different": "farklı", "place": "yer", "started": "başladı", "kept": "tuttu", "best": "en iyi", "soldiers": "askerler", "away": "uzakta", "because": "çünkü", "messages": "mesajlar", "successful": "başarılı", "double agents": "çift taraflı ajanlar", "history": "tarih" },
    questions: [ {q:"Did Juan Pujol García pretend to be a Nazi supporter?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send the Germans fake reports using maps and a tourist book?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he create a fake network of 27 imaginary spies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the British give him the code name 'Agent Garbo'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he convince Hitler the D-Day invasion would happen in a different place?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Hitler send all his best soldiers to the real invasion?", a_en:"No", a_tr:"Hayır"}, {q:"Is he one of the most successful double agents in history?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["10_KimPhilby.mp3"] = [{
    text: "Kim Philby was the most famous and dangerous member of a spy ring known as the 'Cambridge Five.' He was a high-ranking officer in British intelligence and worked closely with the American CIA. For 30 years, he secretly worked for the Soviet Union. Philby was a perfect gentleman who was liked by everyone, which made it easy for him to hide his double life. He gave the Soviets thousands of top-secret documents and the names of many British and American agents. Because of his betrayal, many operations failed and many people were killed. Even when his friends became suspicious, he was so clever that he convinced the government he was innocent. Finally, in 1963, he realized he was going to be caught and escaped to Moscow. He lived the rest of his life in Russia as a hero.",
    dict: { "famous": "ünlü", "dangerous": "tehlikeli", "member": "üye", "spy": "casus", "ring": "halka/şebeke", "known as": "olarak bilinen", "high-ranking": "üst düzey", "officer": "subay/memur", "intelligence": "istihbarat", "worked": "çalıştı", "closely": "yakından", "secretly": "gizlice", "perfect": "mükemmel", "gentleman": "beyefendi", "liked": "sevilen", "everyone": "herkes", "easy": "kolay", "hide": "saklamak", "double life": "ikili hayat", "gave": "verdi", "thousands": "binlerce", "top-secret": "çok gizli", "documents": "belgeler", "names": "isimler", "agents": "ajanlar", "Because of": "yüzünden", "betrayal": "ihanet", "operations": "operasyonlar", "failed": "başarısız oldu", "killed": "öldürüldü", "friends": "arkadaşlar", "suspicious": "şüpheli", "clever": "zeki", "convinced": "ikna etti", "government": "hükümet", "innocent": "masum", "realized": "fark etti", "caught": "yakalanacak", "escaped": "kaçtı", "lived": "yaşadı", "rest": "geri kalan", "life": "hayat", "hero": "kahraman" },
    questions: [ {q:"Was Kim Philby a member of the 'Cambridge Five'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he work closely with the American CIA?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he secretly work for the Soviet Union for 30 years?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the Soviets thousands of top-secret documents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his betrayal cause the failure of no operations?", a_en:"No", a_tr:"Hayır"}, {q:"Did he escape to Moscow in 1963?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live the rest of his life in Russia as a hero?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["11_MataHari.mp3"] = [{
    text: "Mata Hari was a famous exotic dancer from the Netherlands. She traveled all over Europe and became popular with high-ranking military officers and politicians. When World War I started, her ability to travel between countries made her very interesting to intelligence agencies. She was recruited by the French to spy on the Germans, but the Germans also tried to use her. She loved a luxury lifestyle and needed money, which led her into a dangerous double life. In 1917, the French intercepted German radio messages that seemed to prove she was a German agent. The French arrested her and put her on trial for spying. Although the evidence showed no real strength, she was executed by a firing squad near Paris. To this day, people still wonder if she was a real spy or just a victim of the war.",
    dict: { "famous": "ünlü", "exotic": "egzotik", "dancer": "dansçı", "traveled": "seyahat etti", "popular": "popüler", "high-ranking": "üst düzey", "military": "askeri", "officers": "subaylar", "politicians": "politikacılar", "started": "başladı", "ability": "yetenek", "between": "arasında", "countries": "ülkeler", "interesting": "ilginç", "intelligence": "istihbarat", "agencies": "ajanslar", "recruited": "işe alındı", "spy": "casusluk yapmak", "tried": "denedi", "use": "kullanmak", "loved": "sevdi", "luxury": "lüks", "lifestyle": "yaşam tarzı", "needed": "ihtiyacı vardı", "money": "para", "led": "yol açtı/sürükledi", "dangerous": "tehlikeli", "double life": "ikili hayat", "intercepted": "yolunu kesti/yakaladı", "radio": "radyo", "messages": "mesajlar", "seemed": "göründü", "prove": "kanıtlamak", "agent": "ajan", "arrested": "tutukladı", "trial": "duruşma", "spying": "casusluk", "Although": "rağmen", "evidence": "kanıt", "showed": "gösterdi", "no": "hiç", "strength": "güç/sağlamlık", "executed": "idam edildi", "firing squad": "idam mangası", "near": "yakınında", "still": "hala", "wonder": "merak etmek", "real": "gerçek", "victim": "kurban", "war": "savaş" },
    questions: [ {q:"Was Mata Hari an exotic dancer from the Netherlands?", a_en:"Yes", a_tr:"Evet"}, {q:"Was her ability to travel interesting to intelligence agencies?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she live a life with no luxury?", a_en:"No", a_tr:"Hayır"}, {q:"Did the French intercept German radio messages about her?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the French arrest her and put her on trial?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she executed by a firing squad near Paris?", a_en:"Yes", a_tr:"Evet"}, {q:"Do people still wonder if she was a real spy?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["12_MichaelMalone.mp3"] = [{
    text: "Michael Malone was a quiet and patient undercover agent for the United States government. During the 1920s, the famous mob boss Al Capone controlled Chicago with violence. The police found no way to catch him because he was too powerful. Malone was chosen to infiltrate Capone’s gang. He used a fake name and moved into a hotel where the gang members lived. He spent two years as a member of the group, listening to their conversations and finding out who handled the money. Malone discovered that Capone paid no taxes on the millions of dollars he made from crime. He found the secret bookkeepers and convinced them to talk. Because of Malone's undercover work, the government finally put Al Capone in prison for tax evasion. He is the man who truly destroyed the most famous criminal in history.",
    dict: { "quiet": "sessiz", "patient": "sabırlı", "undercover": "gizli", "agent": "ajan", "government": "hükümet", "During": "sırasında", "famous": "ünlü", "mob boss": "mafya patronu", "controlled": "kontrol etti", "violence": "şiddet", "police": "polis", "found": "buldu", "no": "hiç", "way": "yol", "catch": "yakalamak", "powerful": "güçlü", "chosen": "seçildi", "infiltrate": "sızmak", "gang": "çete", "used": "kullandı", "fake": "sahte", "name": "isim", "moved": "taşındı", "hotel": "otel", "members": "üyeler", "spent": "geçirdi", "listening": "dinleyerek", "conversations": "konuşmalar", "finding out": "öğrenerek", "handled": "ilgilendi/yönetti", "money": "para", "discovered": "keşfetti", "paid": "ödedi", "taxes": "vergiler", "millions": "milyonlar", "crime": "suç", "secret": "gizli", "bookkeepers": "muhasebeciler", "convinced": "ikna etti", "talk": "konuşmak", "work": "iş", "finally": "sonunda", "put": "koydu", "prison": "hapishane", "evasion": "kaçırma", "truly": "gerçekten", "destroyed": "yok etti", "criminal": "suçlu", "history": "tarih" },
    questions: [ {q:"Did Michael Malone infiltrate Al Capone's gang?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the police find no way to catch Capone at first?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Malone move into a hotel where the gang members lived?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he discover that Capone paid his taxes perfectly?", a_en:"No", a_tr:"Hayır"}, {q:"Did he find the secret bookkeepers?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the government put Capone in prison for tax evasion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Malone truly destroy the most famous criminal in history?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["13_MordechaiVanunu.mp3"] = [{
    text: "Mordechai Vanunu was a technician who worked at a secret nuclear center in Israel. He began to disagree with nuclear weapons and decided to tell the world what was happening inside. He secretly took more than 50 photos of the secret machines and underground laboratories. He then traveled to London and gave the photos to a famous newspaper. This was a massive event because it proved for the first time that Israel had many nuclear bombs. The Israeli government was very angry. A female agent named 'Cindy' tricked Vanunu in London by pretending to be a tourist. She convinced him to travel to Rome for a holiday. When they arrived, agents kidnapped him and put him on a ship back to Israel. He was put on trial in secret and spent 18 years in prison.",
    dict: { "technician": "teknisyen", "worked": "çalıştı", "secret": "gizli", "nuclear": "nükleer", "center": "merkez", "began": "başladı", "disagree": "aynı fikirde olmamak", "weapons": "silahlar", "decided": "karar verdi", "tell": "anlatmak", "world": "dünya", "happening": "olanlar", "inside": "içinde", "secretly": "gizlice", "took": "çekti (fotoğraf)", "photos": "fotoğraflar", "machines": "makineler", "underground": "yeraltı", "laboratories": "laboratuvarlar", "traveled": "seyahat etti", "gave": "verdi", "famous": "ünlü", "newspaper": "gazete", "massive": "muazzam", "event": "olay", "proved": "kanıtladı", "first time": "ilk kez", "bombs": "bombalar", "government": "hükümet", "angry": "öfkeli", "female": "kadın", "agent": "ajan", "named": "adında", "tricked": "kandırdı", "pretending": "numara yaparak", "tourist": "turist", "convinced": "ikna etti", "holiday": "tatil", "arrived": "vardılar", "kidnapped": "kaçırdılar", "put": "koydular", "ship": "gemi", "back": "geri", "trial": "duruşma", "spent": "geçirdi", "years": "yıllar", "prison": "hapishane" },
    questions: [ {q:"Did Mordechai Vanunu work at a secret nuclear center in Israel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he secretly take more than 50 photos?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the photos to a famous newspaper in London?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the photos prove Israel had no nuclear bombs?", a_en:"No", a_tr:"Hayır"}, {q:"Did a female agent named 'Cindy' trick him?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he kidnapped and put on a ship back to Israel?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he spend 18 years in prison?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["14_NoorInayatKhan.mp3"] = [{
    text: "Noor Inayat Khan was a princess of Indian descent who lived in France and England. When World War II started, she wanted to help fight the Nazis. She was recruited to be a radio operator in occupied Paris. Her mission was very dangerous because the average life of a radio operator in Paris was only six weeks. Her code name was 'Madeleine.' When her entire spy network was arrested, she refused to leave and stayed to be the only link between London and the French Resistance. She moved from house to house every day with her radio to avoid being caught. Finally, someone betrayed her, and the Nazis arrested her. Even though they tortured her, she gave them no secrets. She was executed in a concentration camp in 1944. She is remembered as a hero of incredible courage.",
    dict: { "princess": "prenses", "descent": "kök/soy", "lived": "yaşadı", "started": "başladı", "wanted": "istedi", "help": "yardım etmek", "fight": "savaşmak", "recruited": "işe alındı", "radio": "radyo", "operator": "operatör", "occupied": "işgal edilmiş", "mission": "görev", "dangerous": "tehlikeli", "average": "ortalama", "life": "hayat", "only": "sadece", "weeks": "haftalar", "code name": "kod adı", "entire": "bütün/tüm", "spy": "casus", "network": "ağ", "arrested": "tutuklandı", "refused": "reddetti", "leave": "ayrılmak", "stayed": "kaldı", "link": "bağlantı", "between": "arasında", "Resistance": "Direniş", "moved": "taşındı", "house": "ev", "every day": "her gün", "avoid": "kaçınmak", "caught": "yakalanmak", "Finally": "sonunda", "someone": "birisi", "betrayed": "ihanet etti", "Even though": "rağmen", "tortured": "işkence ettiler", "gave": "verdi", "no": "hiç/yok", "secrets": "sırlar", "executed": "idam edildi", "concentration camp": "toplama kampı", "remembered": "hatırlanır", "hero": "kahraman", "incredible": "inanılmaz", "courage": "cesaret" },
    questions: [ {q:"Was Noor Inayat Khan a princess of Indian descent?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she recruited to be a radio operator in Paris?", a_en:"Yes", a_tr:"Evet"}, {q:"Was the average life of a radio operator in Paris only six weeks?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she refuse to leave when her network was arrested?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she give the Nazis all her secrets when tortured?", a_en:"No", a_tr:"Hayır"}, {q:"Was she executed in a concentration camp?", a_en:"Yes", a_tr:"Evet"}, {q:"Is she remembered as a hero of incredible courage?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["15_OlegPenkovsky.mp3"] = [{
    text: "Oleg Penkovsky was a high-ranking colonel in Soviet military intelligence. He became worried about nuclear war and decided to secretly work for the West. For two years, he provided the CIA with thousands of photos of secret documents about Soviet missiles. His most important contribution happened during the Cuban Missile Crisis in 1962. He gave the Americans the technical manuals for the Soviet missiles being sent to Cuba. This information allowed President Kennedy to know exactly how powerful the missiles were. This knowledge helped Kennedy force the Soviets to remove the missiles and avoid a Third World War. Penkovsky was eventually caught by the KGB and executed in 1963. He is considered a hero for helping to save the world from nuclear destruction.",
    dict: { "high-ranking": "üst düzey", "colonel": "albay", "military": "askeri", "intelligence": "istihbarat", "worried": "endişeli", "nuclear": "nükleer", "war": "savaş", "decided": "karar verdi", "secretly": "gizlice", "work": "çalışmak", "provided": "sağladı", "thousands": "binlerce", "photos": "fotoğraflar", "secret": "gizli", "documents": "belgeler", "missiles": "füzeler", "important": "önemli", "contribution": "katkı", "happened": "oldu", "during": "sırasında", "Crisis": "Kriz", "gave": "verdi", "technical": "teknik", "manuals": "kılavuzlar", "sent": "gönderilen", "information": "bilgi", "allowed": "izin verdi/sağladı", "know": "bilmek", "exactly": "tam olarak", "powerful": "güçlü", "knowledge": "bilgi", "helped": "yardım etti", "force": "zorlamak", "remove": "kaldırmak", "avoid": "kaçınmak/önlemek", "Third": "Üçüncü", "World": "Dünya", "eventually": "sonunda", "caught": "yakalandı", "executed": "idam edildi", "considered": "kabul edilir", "hero": "kahraman", "save": "kurtarmak", "destruction": "yıkım" },
    questions: [ {q:"Was Oleg Penkovsky a colonel in Soviet military intelligence?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he provide the CIA with photos of secret documents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he help the Americans during the Cuban Missile Crisis?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the Americans technical manuals for the missiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Kennedy use this knowledge to start World War III?", a_en:"No", a_tr:"Hayır"}, {q:"Did Kennedy force the Soviets to remove the missiles?", a_en:"Yes", a_tr:"Evet"}, {q:"Is Penkovsky considered a hero for helping save the world?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["16_RichardSorge.mp3"] = [{
    text: "Richard Sorge was a Soviet spy who carried out one of the most successful infiltrations in history. He was a German citizen who joined the Nazi Party and became a famous journalist. He moved to Tokyo and became close friends with the German ambassador. He was so trusted that he was allowed to read top-secret Nazi messages. Every night, Sorge secretly radioed information back to the Soviet Union. His most famous achievement was warning the Soviet leader that Germany was going to invade in 1941. Later, he told them that Japan had no plans to attack Russia. This allowed the Soviet Union to move its best soldiers to defend Moscow, which stopped the German army. Sorge was finally caught by the Japanese and executed in 1944. His information changed the entire direction of World War II.",
    dict: { "spy": "casus", "carried out": "gerçekleştirdi", "successful": "başarılı", "infiltrations": "sızmalar", "history": "tarih", "citizen": "vatandaş", "joined": "katıldı", "Party": "Parti", "became": "oldu", "famous": "ünlü", "journalist": "gazeteci", "moved": "taşındı", "close": "yakın", "friends": "arkadaşlar", "ambassador": "büyükelçi", "trusted": "güvenilen", "allowed": "izin verildi", "read": "okumak", "top-secret": "çok gizli", "messages": "mesajlar", "night": "gece", "secretly": "gizlice", "radioed": "telsizle bildirdi", "information": "bilgi", "back": "geri", "achievement": "başarı", "warning": "uyarma", "leader": "lider", "invade": "işgal etmek", "Later": "daha sonra", "told": "söyledi", "no": "hiç", "plans": "planlar", "attack": "saldırmak", "allowed": "sağladı/izin verdi", "move": "taşımak", "best": "en iyi", "soldiers": "askerler", "defend": "savunmak", "stopped": "durdurdu", "army": "ordu", "finally": "sonunda", "caught": "yakalandı", "executed": "idam edildi", "changed": "değiştirdi", "entire": "bütün/tüm", "direction": "yön" },
    questions: [ {q:"Was Richard Sorge a Soviet spy in Tokyo?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he become close friends with the German ambassador?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he allowed to read top-secret Nazi messages?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he warn the Soviet leader about Germany's invasion?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he tell them Japan had plans to attack Russia?", a_en:"No", a_tr:"Hayır"}, {q:"Did his information allow the Soviet Union to defend Moscow?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his information change the direction of World War II?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["17_RobertHansen.mp3"] = [{
    text: "Robert Hansen was an FBI agent who specialized in catching Russian spies, but he was secretly one of the most damaging spies in American history. For 22 years, he sold thousands of pages of top-secret documents to the Soviet Union and Russia. He met his Russian handlers at no time; instead, he used 'dead drops,' where he would leave packages under a bridge or in a park and pick up bags of cash. He gave the Russians secrets about US nuclear programs and the names of many agents. He even told them about a secret tunnel the FBI built under their embassy. Hansen was a quiet family man, so nobody suspected him for a long time. Finally, the FBI found his fingerprints on a Russian file. He was caught in 2001 and sent to prison for life.",
    dict: { "agent": "ajan", "specialized": "uzmanlaştı", "catching": "yakalama", "spies": "casuslar", "secretly": "gizlice", "damaging": "zarar verici", "history": "tarih", "years": "yıllar", "sold": "sattı", "thousands": "binlerce", "pages": "sayfalar", "top-secret": "çok gizli", "documents": "belgeler", "met": "buluştu", "handlers": "yöneticiler/idareciler", "no time": "hiçbir zaman", "instead": "bunun yerine", "used": "kullandı", "dead drops": "gizli zulalar", "leave": "bırakmak", "packages": "paketler", "under": "altında", "bridge": "köprü", "park": "park", "pick up": "almak", "bags": "çantalar", "cash": "nakit", "gave": "verdi", "secrets": "sırlar", "nuclear": "nükleer", "programs": "programlar", "names": "isimler", "told": "söyledi", "tunnel": "tünel", "built": "inşa etti", "embassy": "büyükelçilik", "quiet": "sessiz", "family man": "aile babası", "nobody": "hiç kimse", "suspected": "şüphelendi", "long time": "uzun zaman", "Finally": "sonunda", "found": "buldu", "fingerprints": "parmak izleri", "file": "dosya", "caught": "yakalandı", "sent": "gönderildi", "prison": "hapishane", "life": "hayat/ömür boyu" },
    questions: [ {q:"Was Robert Hansen an FBI agent?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he sell top-secret documents to the Soviet Union and Russia?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he meet his Russian handlers every day?", a_en:"No", a_tr:"Hayır"}, {q:"Did he use 'dead drops' to exchange packages for cash?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the Russians secrets about US nuclear programs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the FBI find his fingerprints on a Russian file?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he sent to prison for life?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["18_RonStallworth.mp3"] = [{
    text: "Ron Stallworth was the first Black police officer in Colorado Springs. In 1978, he saw an advertisement for the Ku Klux Klan (KKK), a violent racist group. He decided to send a letter pretending to be a white man. To his surprise, the leader of the KKK called him on the phone. Stallworth spent several months talking to the members and even the national leader on the telephone. He learned about their plans to carry out attacks. However, he needed a way to meet them in person. He asked a white police colleague to pretend to be him for the meetings. While the white officer went to the meetings, the real Ron Stallworth continued to lead the investigation on the phone. They successfully infiltrated the group and stopped several acts of violence. His story was later made into a famous movie.",
    dict: { "first": "ilk", "police": "polis", "officer": "memur", "saw": "gördü", "advertisement": "reklam/ilan", "violent": "şiddetli", "racist": "ırkçı", "group": "grup", "decided": "karar verdi", "send": "göndermek", "letter": "mektup", "pretending": "numara yaparak", "white": "beyaz", "man": "adam", "surprise": "sürpriz", "leader": "lider", "called": "aradı", "phone": "telefon", "spent": "geçirdi", "several": "birkaç", "months": "aylar", "talking": "konuşarak", "members": "üyeler", "national": "ulusal", "telephone": "telefon", "learned": "öğrendi", "plans": "planlar", "carry out": "gerçekleştirmek", "attacks": "saldırılar", "However": "ancak", "needed": "ihtiyacı vardı", "way": "yol", "meet": "buluşmak", "in person": "şahsen", "asked": "istedi", "colleague": "meslektaş", "meetings": "toplantılar", "While": "iken", "went": "gitti", "real": "gerçek", "continued": "devam etti", "lead": "yönetmek", "investigation": "soruşturma", "successfully": "başarıyla", "infiltrated": "sızdılar", "stopped": "durdurdular", "acts": "eylemler", "violence": "şiddet", "story": "hikaye", "later": "daha sonra", "made": "yapıldı", "famous": "ünlü", "movie": "film" },
    questions: [ {q:"Was Ron Stallworth the first Black police officer in Colorado Springs?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he send a letter pretending to be a white man to the KKK?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the leader of the KKK call him on the phone?", a_en:"Yes", a_tr:"Evet"}, {q:"Did Stallworth go to the in-person meetings himself?", a_en:"No", a_tr:"Hayır"}, {q:"Did a white police colleague pretend to be him for the meetings?", a_en:"Yes", a_tr:"Evet"}, {q:"Did they successfully infiltrate the group?", a_en:"Yes", a_tr:"Evet"}, {q:"Was his story later made into a famous movie?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["19_RyszardKuklinski.mp3"] = [{
    text: "Ryszard Kukliński was a high-ranking colonel in the Polish army. He had access to all the secret war plans of the Soviet Union. He realized that if a war started, his country would be destroyed. To save Poland, he decided to secretly work for the CIA. For nine years, he took photos of more than 40,000 pages of top-secret Soviet documents. He gave the US the exact plans for a Soviet invasion of Europe. He lived a very stressful double life and was in danger every day. When the Polish security forces began to get close to finding him, the CIA secretly smuggled him and his family out of Poland in a car. He lived in the United States for many years. He is considered a hero because his information helped prevent a Third World War.",
    dict: { "high-ranking": "üst düzey", "colonel": "albay", "army": "ordu", "access": "erişim", "secret": "gizli", "war": "savaş", "plans": "planlar", "realized": "fark etti", "started": "başlarsa", "country": "ülke", "destroyed": "yok edilecek", "save": "kurtarmak", "decided": "karar verdi", "secretly": "gizlice", "work": "çalışmak", "years": "yıllar", "took": "çekti", "photos": "fotoğraflar", "more than": "daha fazla", "pages": "sayfalar", "top-secret": "çok gizli", "documents": "belgeler", "gave": "verdi", "exact": "kesin/tam", "invasion": "işgal", "Europe": "Avrupa", "lived": "yaşadı", "stressful": "stresli", "double life": "ikili hayat", "danger": "tehlike", "every day": "her gün", "When": "olduğunda", "security": "güvenlik", "forces": "kuçler/kuvvetler", "began": "başladı", "close": "yakın", "finding": "bulmaya", "smuggled": "kaçırdı", "family": "aile", "out": "dışarı", "car": "araba", "United States": "Amerika Birleşik Devletleri", "many": "birçok", "considered": "kabul edilir", "hero": "kahraman", "because": "çünkü", "information": "bilgi", "helped": "yardım etti", "prevent": "önlemek", "Third": "Üçüncü", "World": "Dünya" },
    questions: [ {q:"Was Ryszard Kukliński a high-ranking colonel in the Polish army?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he take photos of more than 40,000 pages of Soviet documents?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he give the US plans for a Soviet invasion of Europe?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live a very relaxing and safe life?", a_en:"No", a_tr:"Hayır"}, {q:"Did the CIA smuggle him and his family out of Poland?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he live in the United States for many years?", a_en:"Yes", a_tr:"Evet"}, {q:"Is he considered a hero for helping prevent a Third World War?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["20_TELawrence.mp3"] = [{
    text: "T.E. Lawrence was a British archaeology student and officer who became a famous spy. During World War I, the British sent him to the desert to work with Arab tribes fighting against the Ottoman Empire. Lawrence was no mere watcher of the war; he lived exactly like the Arab people. He wore their clothes, learned their language, and rode camels across the desert. He became a trusted leader and a master of secret warfare. He led missions to blow up trains and cut telegraph lines. His work helped the Arab Revolt succeed and changed the map of the Middle East. He was a controversial figure because he made promises to the Arabs that the British government honored in no way. He wrote a famous book about his adventures and remains a legend of courage and intelligence work.",
    dict: { "archaeology": "arkeoloji", "student": "öğrenci", "officer": "subay", "became": "oldu", "famous": "ünlü", "spy": "casus", "During": "sırasında", "sent": "gönderdi", "desert": "çöl", "work": "çalışmak", "tribes": "kabileler", "fighting": "savaşan", "against": "karşı", "Empire": "İmparatorluk", "no": "hiç/değil", "mere": "sadece", "watcher": "izleyici", "war": "savaş", "lived": "yaşadı", "exactly": "tamamen", "wore": "giydi", "clothes": "kıyafetler", "learned": "öğrendi", "language": "dil", "rode": "bindi", "camels": "develer", "across": "boyunca", "trusted": "güvenilen", "leader": "lider", "master": "usta", "secret": "gizli", "warfare": "savaş", "led": "yönetti", "missions": "görevler", "blow up": "havaya uçurmak", "trains": "trenler", "cut": "kesmek", "telegraph": "telgraf", "lines": "hatlar", "helped": "yardım etti", "Revolt": "İsyan", "succeed": "başarmak", "changed": "değiştirdi", "map": "harita", "Middle East": "Orta Doğu", "controversial": "tartışmalı", "figure": "figür/kişi", "because": "çünkü", "promises": "sözler", "government": "hükümet", "honored": "onurlandırdı/tuttu", "in no way": "hiçbir şekilde", "wrote": "yazdı", "book": "kitap", "adventures": "maceralar", "remains": "kalır", "legend": "efsane", "courage": "cesaret", "intelligence": "istihbarat" },
    questions: [ {q:"Was T.E. Lawrence a British archaeology student?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he work with Arab tribes against the Ottoman Empire?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he wear Arab clothes and learn their language?", a_en:"Yes", a_tr:"Evet"}, {q:"Was he a mere watcher of the war?", a_en:"No", a_tr:"Hayır"}, {q:"Did he lead missions to blow up trains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did his work help the Arab Revolt succeed?", a_en:"Yes", a_tr:"Evet"}, {q:"Did he write a famous book about his adventures?", a_en:"Yes", a_tr:"Evet"} ]
}];

lessonData["21_VirginiaHall.mp3"] = [{
    text: "Virginia Hall was an American woman who wanted to be a diplomat, but she was rejected because she had a wooden leg. When World War II started, she joined the British intelligence service and was the first female spy sent into occupied France. She was an incredible leader and organized many groups of resistance fighters. She helped Allied pilots escape and planned missions to destroy Nazi supplies. The Gestapo called her 'The Limping Lady' and considered her very dangerous. When the Germans almost caught her, she escaped by walking across the snowy mountains on her wooden leg. She later returned to France to help prepare for the D-Day invasion. She received high military medals for her bravery and proved that a disability showed no power to stop a determined person. She is a true hero of the war.",
    dict: { "woman": "kadın", "wanted": "istedi", "diplomat": "diplomat", "rejected": "reddedildi", "because": "çünkü", "wooden": "ahşap/tahta", "leg": "bacak", "started": "başladı", "joined": "katıldı", "intelligence": "istihbarat", "service": "servis", "first": "ilk", "female": "kadın", "spy": "casus", "sent": "gönderilen", "occupied": "işgal edilmiş", "incredible": "inanılmaz", "leader": "lider", "organized": "organize etti", "many": "birçok", "groups": "gruplar", "resistance": "direniş", "fighters": "savaşçılar", "helped": "yardım etti", "Allied": "Müttefik", "pilots": "pilotlar", "escape": "kaçmak", "planned": "planladı", "missions": "görevler", "destroy": "yok etmek", "supplies": "erzak/malzeme", "called": "adlandırdı", "Limping": "Topallayan", "Lady": "Bayan/Hanım", "considered": "kabul etti", "dangerous": "tehlikeli", "almost": "neredeyse", "caught": "yakaladı", "escaped": "kaçtı", "walking": "yürüyerek", "across": "boyunca", "snowy": "karlı", "mountains": "dağlar", "later": "daha sonra", "returned": "geri döndü", "prepare": "hazırlanmak", "invasion": "işgal", "received": "aldı", "high": "yüksek", "military": "askeri", "medals": "madalyalar", "bravery": "cesaret", "proved": "kanıtladı", "disability": "engellilik", "showed": "gösterdi", "no": "hiç", "power": "güç", "stop": "durdurmak", "determined": "kararlı", "person": "kişi", "true": "gerçek", "hero": "kahraman", "war": "savaş" },
    questions: [ {q:"Was Virginia Hall rejected as a diplomat because she had a wooden leg?", a_en:"Yes", a_tr:"Evet"}, {q:"Was she the first female spy sent into occupied France?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she organize groups of resistance fighters?", a_en:"Yes", a_tr:"Evet"}, {q:"Did the Gestapo call her 'The Limping Lady'?", a_en:"Yes", a_tr:"Evet"}, {q:"Did her disability show the power to stop her?", a_en:"No", a_tr:"Hayır"}, {q:"Did she escape by walking across snowy mountains?", a_en:"Yes", a_tr:"Evet"}, {q:"Did she receive high military medals for her bravery?", a_en:"Yes", a_tr:"Evet"} ]
}];
